---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 3m0s
  dependsOn:
    - name: common-infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/base/podinfo
  prune: true
  validation: client