apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    ADMIN_PWD: AgC7nrfITIaaKL+LeK7rxv62Lyy3MZPcbYuMX074lZgwigphnuXsJkheJYuZV6v4VsauaJ5Y/uwKpiLxslP6bjSesSPgi4l3PU1MnXGVkdaGzm2Ya0pg3hSgv2B1MawYw3aDQGIPbIn+LE1175LgWuc+UdC8tLFXnQV4rcHjHm04D2o9xaI5onYggVnQYdJtgziOANhUKLE81SGaDLU7dZI1Au8/fPdHdAWYgzn2PZYZ4I5UK3e3xmk6MzIKmPHktAQxAtGoHpR4h6wz8iOqfd5vg9dNiFYrSlCdBeHkpBMMANMFTE7h3Z/0UlBvG9Jk2pf56ZkhqvOb7tWFRveSPLN+kt4Lm0rpwt49/DWjvAaJcKYR06K/hHa2KfKyO1o3DjajfSdpwngULOR/mmdOycuJi2y+Sqs4oiOk+6icZL/dYZ+7jS+LsW3hHT7LvVfzpOV7ZvKT3bgk+OuLmnsQqVs1+QRYtAFJFZffzD8EbHhQCvIdIc89ty6qeFCBYMFGfLM7cJi6IAwfgGFPzkMaDNILSbHEbv1qtHxreeRTbiOqzqUMeo3TgOXe0H6VbmR/fQxZAhwMUHRDzecDlJGU+FksUqTuL/DD+WWoaRDPhKs7OeGKdQocjxxpP+qceF83T0yKL9Ju8L91yvUc40LBS6K+VJs/8R8vxDURT0IsXQwoqCEwVrejfxva7JSPTlBP/nso1h/A4A4SZw==
    ADMIN_USER: AgCNVMrrwODYircIgONSc3H4zXi2friK32xMK2kXfXcPmIhzRDvVMnq0vKadEAEgmdE8gwnOPgTpCb5ZvPesGmcYXrp5B7NqvhjIRhtTqpbk/7K4UwI4YR9tgHxfIIk4UWSzqEVT9DGYo1f3KPWcPslxS38g2USjt3mFZl3S9ezQzEIzsF/7XzEgch1+dF4Pmwxzc7EBORNhBH/UyIW9PncQE+0xpF/EsSOf30cpxjOcEVZcqHOE/nLCHVKTTCXsCy+Yh+jgJ6STDPKh54U19tBKOOkPCtlkuGB4OwuZ4s6PI3RSPa+JSoIUfqcXGSzlUQ2qDjlE1p4YVGFFV7bJHPO86dYmdsNf1wuOY0L7V0f6qPiSk9imUaAkZGHSqxcUtUdbYVMemHuHXyT+0iytB/4hU4+GGfA4qAZQ4mYSMYpT+Xn8pkZ9jBiomISpdR/FuUjP2s1ihIuNrIptitDwIw+AwfB+PfpE78y0XZrkr/5HkcyRHhBWZ91ex9j/KPlAvLmawuvN+AYUcQDcwSrDIhih9QxhSLtDNWPyXA2m0J548eQ7jz/RlV6jNrED0PaV/1kxcZWLwKGfLuZJEOIkWqrhuv63uYhevbiMqALlKZM8Pcs0QlItzByfeHQfopRhG6/r06DNFNNs2mdAGjlfUybhVd2YywFm25GAvQz/BLa0uUAd+e63/Xltzln2/MQwEsED1Of0Wg==
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default

